### 회원가입
POST http://localhost:8080/member/signUp
Content-Type: application/json

{
  "manager": true,
  "id": "emfprhs105@naver.com",
  "password": "123",
  "name": "TaeYoung",
  "phone": "010-5123-1234"
}


###이메일 인증
GET http://localhost:8080/member/signUp/verify?key=$2a$10$io/ZrUQOYqLAucI1l0AskeL0jnc1iZ0VOK2OrE.O1911ytMfrFNay


### 로그인
POST http://localhost:8080/member/signIn
Content-Type: application/json

{
  "userId": "emfprhs105@naver.com",
  "password": "123"
}



