### 매장 등록
POST http://localhost:8080/member/shop/register?managerId=4
Content-Type: application/json

{
  "managerId": 2,
  "name": "맥도날드2",
  "locate": "중랑구",
  "description": "중랑구 상봉동",
  "reserveLimit": 10
}

### 매장 수정
PUT http://localhost:8080/member/shop/register?shopId=1
Content-Type: application/json

{
  "name": "맥도날드3",
  "locate": "중랑구",
  "description": "위치변경하였습니다."
}

### 매장 삭제
DELETE http://localhost:8080/member/shop/register?shopId=2

