### 회원가입
POST http://localhost:8080/member/signUp
Content-Type: application/json

{
  "manager": false,
  "id": "pty10510@gmail.com",
  "password": "123",
  "name": "TaeJin",
  "phone": "010-5123-1234"
}


###이메일 인증
GET http://localhost:8080/member/signUp/verify?key=39a65c62-c05d-4c8f-b9e2-7a6e87e6222d


### 로그인
POST http://localhost:8080/member/signIn
Content-Type: application/json

{
  "userId": "pty10510@gmail.com",
  "password": "123"
}



