### 매장 등록
POST http://localhost:8080/manager/shop?managerId=4
Content-Type: application/json

{
  "managerId": 0,
  "name": "맥도날드2",
  "locate": "동대문구",
  "description": "동대문구에 있는 맥도날드 프랜차이즈"
}

### 매장 수정
PUT http://localhost:8080/manager/shop?shopId=1
Content-Type: application/json

{
  "name": "맥도날드3",
  "locate": "중랑구",
  "description": "위치변경하였습니다."
}

### 매장 삭제
DELETE http://localhost:8080/manager/shop?shopId=2

